language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: kC35rSOTsFLk7rWoAH9bz6GrMl/cDZs+O8p/GJOucgkpofyCS59BH3PS16fWyRRmKDiXwJ55PgF4pvHqSm5+b3+djiKBt7gtZtYBH0H2+vO3Q0aTi3nKi5zS+j2mCe4lUwHW7QPbBDjbI43wuVQGFw7rFLnHw/kdi9wr0Abb6i5nFS/z+HJzK2lvZ5qdqILGMLmeCKBs494I4BnJ/xhYjZCx7vbYPjzXgxH39OkbtAfmdvIydstUOjM1sOyu2OElWVsyes7zHJs7yvac1BKpdtTdtxXP4pwvI3DtfiJ4SVtfWQGKI5F0A8lpM7x89SsUO8oFH7I5MBR0C4ukaauEKc5KJD1TA70ld17owm+FYugWeqa0qM3W9q01yvPpKDRFNHhka4B3ZzG7WL+e5A9yivdBu8BqrMKRNy3FdF7fzGyftcgeVIb+JWwtqZPm6hoxXb2QAtp68rR2cz/tsFCwzvSfP+vo7mfdSq2Ddik3ITwkg38rfHLiGdiUdrklmlOce53jpF4I0czT5qmSEbhUcBZp8E1/gJYdQ5XEVGVLgNv7IJHX8SyNy6x/O4IQv5z0a0+rqxqykQBxOW+xoigsmSCM7nQEzQqaX2mcz9HAe0rcdV6Kr8kPKBMh7wfWz941Z/mNl6CvRA4Rq2jaehpvbLzD8h3NG9YPwdCyTKCO83w=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: jEiYY6i7twxmqLey2PWo71SLumrAR7NEjndrfmxP0WTrDnQfethSXjtp4zhyrzTqbcXozMpG/CkaZf1DZ6hS74H+8zGEXW3YdwIz+dsv89IYvM01JhQsjWOjp3LEjMkQj4VljHorTqSR4jEZYDff+ypKJvKi9MwSYcrQvLxRfLFADUL4ly9D+KPmfxfunIoyipUWIyxKjOSzQ0mZqiMV+U69C0WDu5anU/AsE5ba4T510O9+7D5bPzZhATwRI5GBaEHJFiNI4Dk8MFI6x59y/kQad0RsYU3rJOCdTin5md8UARjVDek7ZyMEovWCwZVm78wDo+H/UVFjCyiTgjbFgWdx/PfNyTysX8PMpF9PxGG668nyWj/EG18t8v/YEatE+Qheuuj/E3XNgwlCUBmFPFrc782nnGSV3InGXS7J5EXwnejQaSErQf9EN7lKG5Q8xNpWB+Nb30A14mmKOeZYvptaQ11dMbp/1fA0Nt7675Qp2uf6UQfg+VolFT/4rGLNDadWy9gCfC9lR/BwBmCbYFDcjxKTjB7yeEKB7TPrz14AHeYVvtLVFBqx6iDOTuVyxr8xOH1MzHIbj4uU2XJTkPq+x8bW2Hvls5PgL6dutgYiwz+jZj34fepVM6I5GQSuaakiSiRetzD9Aq+S4mh4QF7l1/uuHLyjq6srzm1X1zY=
sudo: false
